---
title: "Multilevel Modeling Review"
author: "William Murrah"
date: "September 8, 2015"
output: html_document
---

```{r}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, results = 'asis')
```

```{r }
# Packages used
library(lme4)
library(texreg)
library(stargazer)
library(psychometric)
library(psych)
library(sjmisc)
library(sjPlot)
library(lattice)
library(mosaic)
```

```{r , results = 'asis'}
grad <- read.table("ch7grad1.txt", header = FALSE)
names(grad) <- c("id", "grad1", "grad2", "grad3", "grad4",
                 "private", "prestige")
stargazer(grad, type = "html")
```

```{r }
# Using reshape() to transform data from wide to long.
gradlong <- reshape(data = grad,                   # Wide data frame.
                    varying = c("grad1", "grad2",  # Time-varying variables,
                                "grad3", "grad4"), #   only one here.
                    v.names = "graduate",          # Name for stacked variable.
                    timevar = "growrate",          # Name for timing variable.
                    times = 0:3,                   # Values for timing variable.
                    idvar = "id",                  # Id variable.
                    direction = "long")            # Indicate going to long.
# Rename rownames
rownames(gradlong) <- 1:nrow(gradlong)
# Reorder data frame by 'id' variable.
gradlong <- gradlong[order(gradlong$id), ]

mean(graduate, data = gradlong, groups = growrate)
sd(graduate, data = gradlong, groups = growrate)
```

## Individual Growth Trajectories
```{r , results = 'asis'}
# Plot individual growth trajectories with lattice package.
xyplot(graduate ~ growrate , 
       data = gradlong, 
       group =id, 
       type = "b",
       col = "black")
```

```{r}
mod0 <- lmer(graduate ~ 1 + (1 |id), gradlong, REML = FALSE)
htmlreg(mod0)

# Calculate ICC.
252.03/(252.03 + 112.75)

mod1 <- lmer(graduate ~ growrate + (growrate | id), 
             data = gradlong, REML = FALSE)
htmlreg(list(mod0, mod1))

```

```{r }
ctr <- function(x) scale(x, scale = FALSE)
gradlong$prestige <- ctr(gradlong$prestige)
gradlong$private <- ctr(gradlong$private)
mod2 <- lmer(graduate ~ growrate*private + growrate*prestige + (growrate | id),
             data = gradlong, REML = FALSE)
htmlreg(list(mod0, mod1, mod2))
```
# Look at Mplus output.

## Example with varying occasions 

```{r , }
curran <- read_spss("CurranLong.sav")

# view_df(curran, showFreq = TRUE, showPerc = T)
stargazer(curran, type = "html")

# How many children are in our data?
length(unique(curran$id))

xyplot(read ~ kidagetv, 
       data = curran, 
       groups = id, 
       type = "o",
       col = "black")


mod0 <-   lmer(read ~ poly(kidage6, 2, raw = TRUE) + (1 | id), 
               curran, REML = FALSE)
htmlreg(mod0)
mod0.2 <- lmer(read ~ kidage6 + kidagesq + (1 | id), curran, 
               REML = FALSE)
htmlreg(list(mod0, mod0.2))
```



# Latent Growth Modeling 

```{r}
rm(list = ls())
# Some Key points:
# 1. Not a multilevel model (yet).
# 2. Intercept and slope are latent variables.
# 3. Latent variables measured by repeated observations of y.
# 4. Therefore, we use wide format data.

grad <- read.table("ch7grad1.txt", header = FALSE)
names(grad) <- c("id", "grad1", "grad2", "grad3", "grad4",
                 "private", "prestige")
stargazer(grad, type = "html")
```




